# Generated by Django 4.0.2 on 2022-02-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutorapp', '0005_captchacaptchastore_postofficeattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinetutorappDjangomigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'onlinetutorapp_djangomigrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlinetutorappFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'onlinetutorapp_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlinetutorappPelcon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'onlinetutorapp_pelcon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlinetutorappYoutube',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_names', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('v_watched', models.IntegerField(blank=True, null=True)),
                ('satisfied', models.IntegerField()),
                ('viewer_like', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'onlinetutorapp_youtube',
                'managed': False,
            },
        ),
    ]
