# Generated by Django 4.0.2 on 2022-02-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutorapp', '0008_delete_coursetopic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlinetutorappDjangomigrations',
        ),
    ]
