# Generated by Django 4.0.2 on 2022-02-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutorapp', '0009_delete_onlinetutorappdjangomigrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionselection',
        ),
        migrations.DeleteModel(
            name='Quizquestion',
        ),
        migrations.DeleteModel(
            name='Userquizselection',
        ),
    ]
