# Generated by Django 4.0.1 on 2022-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlinetutorappDjangomigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'onlinetutorapp_djangomigrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idtest', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='Userid', primary_key=True, serialize=False)),
                ('staffid', models.IntegerField(db_column='Staffid')),
                ('name', models.CharField(db_collation='utf8_general_ci', db_column='Name', max_length=30)),
                ('email', models.CharField(db_collation='utf8_general_ci', db_column='Email', max_length=100)),
                ('password_hash', models.CharField(db_column='Password_hash', max_length=64)),
                ('isactive', models.TextField(blank=True, db_column='isActive', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
    ]
