# Generated by Django 4.0.2 on 2022-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutorapp', '0005_files_pelcon_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaCaptchastore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=32)),
                ('response', models.CharField(max_length=32)),
                ('hashkey', models.CharField(max_length=40, unique=True)),
                ('expiration', models.DateTimeField()),
            ],
            options={
                'db_table': 'captcha_captchastore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfficeAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=255)),
                ('headers', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_office_attachment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfficeAttachmentEmails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_office_attachment_emails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfficeEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_email', models.CharField(max_length=254)),
                ('to', models.TextField()),
                ('cc', models.TextField()),
                ('bcc', models.TextField()),
                ('subject', models.CharField(max_length=989)),
                ('message', models.TextField()),
                ('html_message', models.TextField()),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('backend_alias', models.CharField(max_length=64)),
                ('number_of_retries', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'post_office_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfficeEmailtemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('html_content', models.TextField()),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('language', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'post_office_emailtemplate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostOfficeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField()),
                ('exception_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'post_office_log',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Pelcon',
        ),
        migrations.DeleteModel(
            name='YouTube',
        ),
    ]
